using Content.Shared._Starlight.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;

namespace Content.Client.Options.UI;

/// <summary>
/// First-run prompt offering the liquid glass theme with a live preview checkbox.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GlassThemePrompt : DefaultWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;

    public GlassThemePrompt()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        GlassCheckBox.Pressed = _cfg.GetCVar(StarlightCCVars.UIGlassTheme);
        GlassCheckBox.OnToggled += args => _cfg.SetCVar(StarlightCCVars.UIGlassTheme, args.Pressed);
        ConfirmButton.OnPressed += _ =>
        {
            _cfg.SetCVar(StarlightCCVars.UIGlassThemeSeen, true);
            Close();
        };
    }
}
