using System.Numerics;
using Content.Shared._Starlight.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;

namespace Content.Client.PDA;

[Virtual]
[GenerateTypedNameReferences]
public partial class PdaWindow : BaseWindow
{
    [Dependency] private IConfigurationManager _cfg = default!;

    private Color _borderBase = Color.White;
    private Action<bool>? _onGlassChanged;

    public string? BorderColor
    {
        get => Background.ActualModulateSelf.ToHex();

        set
        {
            _borderBase = Color.FromHex(value, Color.White);
            ApplyBorder();
        }
    }

    public string? AccentHColor
    {
        get => AccentH.ActualModulateSelf.ToHex();

        set
        {
            AccentH.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentH.Visible = value != null;
        }
    }

    public string? AccentVColor
    {
        get => AccentV.ActualModulateSelf.ToHex();

        set
        {
            AccentV.ModulateSelfOverride = Color.FromHex(value, Color.White);
            AccentV.Visible = value != null;
        }
    }

    public PdaWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _onGlassChanged = _ => ApplyBorder();
        _cfg.OnValueChanged(StarlightCCVars.UIGlassTheme, _onGlassChanged, true);

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;

        AccentH.Visible = false;
        AccentV.Visible = false;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        if (_onGlassChanged != null)
            _cfg.UnsubValueChanged(StarlightCCVars.UIGlassTheme, _onGlassChanged);
    }

    private const float PdaGlassAlpha = 0.55f;

    private void ApplyBorder()
    {
        var color = _borderBase;
        if (_cfg.GetCVar(StarlightCCVars.UIGlassTheme))
            color = new Color(color.R, color.G, color.B, color.A * PdaGlassAlpha);
        Background.ModulateSelfOverride = color;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}
