using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Manual lobby music switcher (previous / current track / next).
/// Replaces the servers hub in the lobby. Wired up by <see cref="LobbyState"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LobbyMusicSwitcher : BoxContainer
{
    public LobbyMusicSwitcher()
    {
        RobustXamlLoader.Load(this);
    }
}
