using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Maths;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Manual lobby music switcher (previous / current track / next) with a rocking vinyl.
/// Replaces the servers hub in the lobby. Wired up by <see cref="LobbyState"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LobbyMusicSwitcher : BoxContainer
{
    private static readonly string[] RockFrames =
    {
        "/Textures/_Starlight/Interface/Vinyl/vinyl.png",
        "/Textures/_Starlight/Interface/Vinyl/vinyl_flipped.png",
    };

    private const int RockMs = 180;

    private int _rockIndex;
    private int _rockDirection = 1;
    private bool _rocking;

    public LobbyMusicSwitcher()
    {
        RobustXamlLoader.Load(this);
        VinylRect.OnKeyBindDown += OnVinylInput;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _rocking = true;
        RockTick();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _rocking = false;
    }

    private void RockTick()
    {
        if (!_rocking)
            return;

        // No rocking while bouncing.
        if (!_bouncing)
        {
            _rockIndex += _rockDirection;
            if (_rockIndex >= RockFrames.Length - 1 || _rockIndex <= 0)
                _rockDirection *= -1;
            VinylRect.TexturePath = RockFrames[_rockIndex];
        }
        Timer.Spawn(RockMs, RockTick);
    }

    private bool _bouncing;

    private void OnVinylInput(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick || _bouncing)
            return;

        _bouncing = true;
        BounceTick(0);
    }

    private void BounceTick(int step)
    {
        if (!_bouncing)
            return;

        switch (step)
        {
            case 0:
                VinylRect.Margin = new Thickness(0f, -14f, 0f, 14f);
                break;
            case 1:
                VinylRect.Margin = new Thickness(0f, -26f, 0f, 26f);
                break;
            case 2:
                VinylRect.Margin = new Thickness(0f, -8f, 0f, 8f);
                break;
            default:
                VinylRect.Margin = new Thickness(0f);
                _bouncing = false;
                return;
        }
        Timer.Spawn(90, () => BounceTick(step + 1));
    }
}
