using Content.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Clickable lobby playlist queue. Clicking a track switches to it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LobbyMusicQueueWindow : DefaultWindow
{
    [Dependency] private IResourceCache _resCache = default!;

    private ContentAudioSystem? _audio;

    public LobbyMusicQueueWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _audio = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<ContentAudioSystem>();
        OnOpen += RebuildList;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        OnOpen -= RebuildList;
        if (_audio != null)
            _audio.LobbySoundtrackChanged -= OnTrackChanged;
    }

    private void OnTrackChanged(LobbySoundtrackChangedEvent ev)
    {
        RebuildList();
    }

    private void RebuildList()
    {
        TrackList.RemoveAllChildren();
        if (_audio?.LobbyPlaylistTracks is not { } playlist)
            return;

        _audio.LobbySoundtrackChanged -= OnTrackChanged;
        _audio.LobbySoundtrackChanged += OnTrackChanged;

        var current = _audio.CurrentLobbyTrack;
        foreach (var filename in playlist)
        {
            var name = TrackDisplayName(filename);
            var button = new Button
            {
                Text = filename == current ? $"▶ {name}" : name,
                HorizontalExpand = true,
                Disabled = filename == current,
            };
            var file = filename;
            button.OnPressed += _ => _audio?.PlayLobbyTrack(file);
            TrackList.AddChild(button);
        }
    }

    private string TrackDisplayName(string filename)
    {
        if (!_resCache.TryGetResource<AudioResource>(filename, out var resource))
            return filename;

        var stream = resource.AudioStream;
        var title = string.IsNullOrEmpty(stream.Title) ? "?" : stream.Title;
        var artist = string.IsNullOrEmpty(stream.Artist) ? "?" : stream.Artist;
        return $"{title} — {artist}";
    }
}
