using System.Collections.Generic;
using System.Linq;
using Content.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.IoC;
using Robust.Shared.Utility;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Clickable lobby playlist queue. Clicking a track switches to it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LobbyMusicQueueWindow : DefaultWindow
{
    [Dependency] private IResourceCache _resCache = default!;

    private static readonly Dictionary<string, string> NameCache = new();

    private ContentAudioSystem? _audio;
    private readonly List<(Button Button, string Filename)> _rows = new();
    private List<string>? _pendingTracks;
    private int _buildId;

    public LobbyMusicQueueWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _audio = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<ContentAudioSystem>();
        // NOTE: subscribing fires the handler immediately with the current track,
        // so subscribe exactly once here (re-subscribing inside RebuildList recursed infinitely).
        _audio.LobbySoundtrackChanged += OnTrackChanged;
        OnOpen += RebuildList;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        OnOpen -= RebuildList;
        if (_audio != null)
            _audio.LobbySoundtrackChanged -= OnTrackChanged;
    }

    private void OnTrackChanged(LobbySoundtrackChangedEvent ev)
    {
        RebuildList();
    }

    private void RebuildList()
    {
        _buildId++;
        TrackList.RemoveAllChildren();
        _rows.Clear();
        if (_audio?.LobbyPlaylistTracks is not { } playlist)
            return;

        _pendingTracks = new List<string>(playlist);
        PumpQueue(_buildId);
    }

    /// <summary>
    /// Adds rows a few at a time so opening the queue doesn't hitch the client.
    /// </summary>
    private void PumpQueue(int id)
    {
        if (id != _buildId || TrackList.Disposed)
            return;

        var current = _audio?.CurrentLobbyTrack;
        for (var i = 0; i < 8 && _pendingTracks is { Count: > 0 }; i++)
        {
            var filename = _pendingTracks[0];
            _pendingTracks.RemoveAt(0);
            var name = TrackDisplayName(filename, false) ?? filename;
            var file = filename;
            var button = new Button
            {
                Text = filename == current ? $"▶ {name}" : name,
                HorizontalExpand = true,
                Disabled = filename == current,
            };
            button.OnPressed += _ => _audio?.PlayLobbyTrack(file);
            TrackList.AddChild(button);
            _rows.Add((button, filename));
        }

        if (_pendingTracks is { Count: > 0 })
        {
            Timer.Spawn(30, () => PumpQueue(id));
            return;
        }

        PumpNames(id);
    }

    /// <summary>
    /// Resolves missing track titles gradually after the window is already shown.
    /// </summary>
    private void PumpNames(int id)
    {
        if (id != _buildId || TrackList.Disposed)
            return;

        var row = _rows.FirstOrDefault(r => !NameCache.ContainsKey(r.Filename));
        if (row == default)
            return;

        if (!NameCache.ContainsKey(row.Filename))
            NameCache[row.Filename] = TrackDisplayName(row.Filename, true) ?? row.Filename;

        var name = NameCache[row.Filename];
        row.Button.Text = row.Filename == _audio?.CurrentLobbyTrack ? $"▶ {name}" : name;
        Timer.Spawn(50, () => PumpNames(id));
    }

    private string? TrackDisplayName(string filename, bool allowLoad)
    {
        if (NameCache.TryGetValue(filename, out var cached))
            return cached;

        if (!allowLoad)
            return null;

        if (!_resCache.TryGetResource<AudioResource>(filename, out var resource))
            return null;

        var stream = resource.AudioStream;
        var title = string.IsNullOrEmpty(stream.Title) ? "?" : stream.Title;
        var artist = string.IsNullOrEmpty(stream.Artist) ? "?" : stream.Artist;
        return $"{title} — {artist}";
    }
}
