using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Maths;
using Timer = Robust.Shared.Timing.Timer;

namespace Content.Client.Lobby.UI;

/// <summary>
/// Manual lobby music switcher (previous / current track / next) with a rocking vinyl.
/// Replaces the servers hub in the lobby. Wired up by <see cref="LobbyState"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LobbyMusicSwitcher : BoxContainer
{
    private static readonly string[] RockFrames =
    {
        "/Textures/_Starlight/Interface/Vinyl/vinyl_0.png",
        "/Textures/_Starlight/Interface/Vinyl/vinyl_1.png",
        "/Textures/_Starlight/Interface/Vinyl/vinyl_2.png",
        "/Textures/_Starlight/Interface/Vinyl/vinyl_3.png",
        "/Textures/_Starlight/Interface/Vinyl/vinyl_4.png",
        "/Textures/_Starlight/Interface/Vinyl/vinyl_5.png",
    };

    private const int RockMs = 180;

    private int _rockIndex;
    private int _rockDirection = 1;
    private bool _rocking;

    public LobbyMusicSwitcher()
    {
        RobustXamlLoader.Load(this);
        VinylRect.OnKeyBindDown += OnVinylInput;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _rocking = true;
        RockTick();
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _rocking = false;
    }

    private void RockTick()
    {
        if (!_rocking)
            return;

        // Rocking continues even mid-bounce.
        _rockIndex += _rockDirection;
        if (_rockIndex >= RockFrames.Length - 1 || _rockIndex <= 0)
            _rockDirection *= -1;
        VinylRect.TexturePath = RockFrames[_rockIndex];
        Timer.Spawn(RockMs, RockTick);
    }

    private bool _bouncing;

    private void OnVinylInput(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick || _bouncing)
            return;

        _bouncing = true;
        BounceTick(0);
    }

    private void BounceTick(int step)
    {
        if (!_bouncing)
            return;

        // High jump with a second smaller bounce on landing.
        // Clicks are ignored until the whole sequence finishes.
        switch (step)
        {
            case 0:
                VinylRect.Margin = new Thickness(0f, -20f, 0f, 20f);
                break;
            case 1:
                VinylRect.Margin = new Thickness(0f, -44f, 0f, 44f);
                break;
            case 2:
                VinylRect.Margin = new Thickness(0f, -16f, 0f, 16f);
                break;
            case 3:
                VinylRect.Margin = new Thickness(0f);
                break;
            case 4:
                VinylRect.Margin = new Thickness(0f, -10f, 0f, 10f);
                break;
            default:
                VinylRect.Margin = new Thickness(0f);
                _bouncing = false;
                return;
        }
        Timer.Spawn(90, () => BounceTick(step + 1));
    }
}
